# Generated by Django 4.2 on 2023-07-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuarioname',
            new_name='username',
        ),
    ]
